### PR TITLE
Fix NetBSD meminfo build

### LINKED ISSUE #64: NetBSD legacy build fails: netbsd-meminfo.c uses int64 and missing vmtotal header
Legacy Makefile build on NetBSD fails when compiling client/netbsd-meminfo.c. The file uses non-standard int64 and references struct vmtotal without including the header that defines it.

Error output:
```
netbsd-meminfo.c:25:2: error: unknown type name ‘int64’; did you mean ‘int64_t’?
netbsd-meminfo.c:31:17: error: storage size of ‘vmdata’ isn’t known
```

Environment:
- OS: NetBSD 10.1 (amd64)
- Build: legacy Makefiles (GNU make)

Repro (simplified):
1. ./configure.server (defaults)
2. gmake -j2
3. Failure in client/netbsd-meminfo.c

Suggested fix:
- Include <sys/vmmeter.h>
- Use int64_t instead of int64

Minimal diff:
```c
#include <sys/vmmeter.h>
...
int64_t physmem;
```

### PR DESCRIPTION
**Pull request by bonomani**
Fixes #64.
This updates client/netbsd-meminfo.c to include <sys/vmmeter.h> and use int64_t for physmem, resolving NetBSD build errors in the legacy Makefile build.

### CODE REVIEW

File: client/netbsd-meminfo.c [hunk 1]
```diff
@@ -22,7 +23,7 @@ static char rcsid[] = "$Id$";
 int main(int argc, char *argv[])
 {
 	int hw_physmem[] = { CTL_HW, HW_PHYSMEM64 };
-	int64 physmem;
+int64_t physmem;
```
Comment (RolandRosenfeld) [inline client/netbsd-meminfo.c]: Please fix indentation here (your change removes the indentation).

**Review by RolandRosenfeld — APPROVED** [review]
Looks good now.
